# Generated by Django 4.2.30 on 2026-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('product', models.CharField(choices=[('wiremesh', 'Crimped Wiremesh Screen'), ('perforated', 'Punching Perforated Plate'), ('both', 'Both Products'), ('other', 'Other / Not Sure')], max_length=20, verbose_name='Product Required')),
                ('message', models.TextField(verbose_name='Message / Specifications')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
