# Generated by Django 4.2.30 on 2026-06-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField()),
                ('order_date', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_nos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_nos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_items', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order_no'],
            },
        ),
    ]
